# Generated by Django 3.1 on 2023-09-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Picture',
        ),
    ]
